---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubecloudscaler-cloud-v1alpha3-flow
  failurePolicy: Fail
  name: vflow-v1alpha3.kb.io
  rules:
  - apiGroups:
    - kubecloudscaler.cloud
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - flows
  sideEffects: None
