# This rule is not used by the project kubecloudscaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kubecloudscaler.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubecloudscaler
    app.kubernetes.io/managed-by: kustomize
  name: flow-viewer-role
rules:
- apiGroups:
  - kubecloudscaler.cloud
  resources:
  - flows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubecloudscaler.cloud
  resources:
  - flows/status
  verbs:
  - get
