# permissions for end users to edit scalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudscaler
    app.kubernetes.io/managed-by: kustomize
  name: scaler-editor-role
rules:
  - apiGroups:
      - k8s.kubecloudscaler
    resources:
      - scalers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.kubecloudscalerr
    resources:
      - scalers/status
    verbs:
      - get
